### ISSUE TITLE
 Amazon EMR-Managed Security Groups terminology 

### ISSUE THREAD

**Issue by sunojram** [awsdocs/amazon-emr-management-guide#25]
https://github.com/awsdocs/amazon-emr-management-guide/blob/master/doc_source/emr-man-sec-groups.md references `master` and `slave` terminology which must be replaced by `manager` and `worker`.

**Comment by Pahtoe** [comment]
@sunojram Thanks for the callout. We actually purged this legacy terminology from our content wherever possible some time ago, despite the fact that the [Hadoop documentation ](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HdfsDesign.html) still uses master/slave terminology. We use master node and core/task nodes in the context of EMR clusters. Unfortunately, there are some legacy API and service component terms (such as the names of Security Groups on the page that you reference) whose names have not been changed because of the impact it would have to customers with existing implementations. I'll pass this issue on to the Engineering team to consider. Thanks again for the feedback.
